services:
  - type: web
    name: snet
    env: python
    region: frankfurt  # אזור באירופה לביצועים טובים יותר עבור משתמשים מישראל
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: PORT
        value: 5001
      - key: SENTRY_DSN
        sync: false  # יש להגדיר ידנית ב-Render dashboard
      - key: GA_MEASUREMENT_ID
        sync: false  # יש להגדיר ידנית ב-Render dashboard
      - key: SECRET_KEY
        generateValue: true  # Render ייצר מפתח מאובטח אוטומטית
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 